### ISSUE TITLE
Schemas for Entities

### ISSUE THREAD

**Issue by ChakshuGautam** [INCOMS/vc-specs#7]
I think there would be merit in creating an entity schema repository - something like [schema.org](https://schema.org/). This will help everyone to be on the same page on the properties that are available and use the same on the VC specs. 

If this already exists, please point me to the same.

**Comment by pramodkvarma** [comment]
This repo (or repos, we may create more) are meant to have these schemas only. As India adopts this across academic, skilling, and employment/work domains, it is necessary to have comprehensive and interoperable schemas. This project is meant to create such schemas. If there are specific suggestions in organizing these within these repos, you are most welcome to help.

**Comment by ChakshuGautam** [comment]
I think we can start by using the [schema.org's](https://schema.org/). The [JsonLd](https://github.com/schemaorg/schemaorg/blob/main/data/releases/11.0/schemaorg-all-https.jsonld) is already available so we can start adding context for our use cases and enriching them once we start creating the specs.

I can create a small CI workflow to verify if the VC specs are conforming to this JsonLd and suggest changes if similar fields are used with a different field.

In the long run, a playground that would allow everyone to create VCs and highlight/suggest certain schema/fields when the user is not conforming to the above spec would allow for faster creation of specs.

<img width="1668" alt="Screenshot 2022-04-13 at 6 35 31 PM" src="https://user-images.githubusercontent.com/7413816/163186615-7ea3f263-3981-4e0f-a05e-ba5cc0377d15.png">

Please let me know if this would help make it easier to contribute.

**Comment by ChakshuGautam** [comment]
I think I missed [this](https://github.com/INCOMS/vc-specs/blob/main/common/schema.org.json). The repo already uses schema.org. Closing this issue for now. I will create a new one for the playground.

**Comment by pramodkvarma** [comment]
:-) thanks!
